# Dependencies
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Edwin,
tagline:          'About me'
description:      'I am an iOS developer at <a href="http://redant.com">RedAnt</a> I also work with python, mongodb, android and ruby on rails. Stalk me on <a href="uk.linkedin.com/in/edwinbosire/">LinkedIn</a>.'
url:              http://twitter.com/edwinbosire

author:
  name:           'Edwin Bosire'
  url:            https://twitter.com/edwinbosire

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/edwinbosire
  
social:
    twitter       https://twitter.com/edwinbosire
    linkedin      http://uk.linkedin.com/in/edwinbosire/