# Dependencies
theme: chesterhow/tale
permalink:  /:year-:month-:day/:title
paginate: 5

plugins:
  - jemoji
  - jekyll-feed
  - jekyll-paginate
  - jekyll-remote-theme

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# SITE CONFIGURATION
baseurl: ""
url: "https://edwinbosire.github.io"

markdown: kramdown
highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Edwin Bosire'
tagline:          'About me'
description:      'A Software Engineer with particular interest in mobile applications.'
url:              http://twitter.com/edwinbosire
resume:           '/resume.html'

author:
  name:           'Edwin Bosire'
  url:            https://twitter.com/edwinbosire

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/edwinbosire

twitter: https://twitter.com/edwinbosire
  
linkedin: uk.linkedin.com/in/edwinbosire/

# This is the list of pages to incldue in the header of the website.
pages_list:
  About: '/about/'
  Archive: '/archive/'
  Feed: '/atom.xml'
